services:
  app:
    build:
      dockerfile: Dockerfile.dev
    command: npm run dev
    restart: unless-stopped
    volumes:
      - ./app:/var/app
      - /var/app/node_modules
      - /var/app/.next
  event-server:
    build:
      dockerfile: Dockerfile.dev
    command: npm run dev
    restart: unless-stopped
    volumes:
      - ./event-server:/var/app


