FROM node:18-alpine

RUN apk add --no-cache openssl
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /var/app

COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma

RUN pnpm install
RUN pnpm prisma generate

COPY . .

COPY next.config.mjs ./next.config.mjs
