name: Build, lint, test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.1

      - name: Setup Node.js 20
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: app/pnpm-lock.yaml

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run tests and generate coverage
        run: npm run test:ci

      - name: Upload coverage report
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          title: Code coverage
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: app/coverage/lcov.info
